### ISSUE TITLE
Impossible to get the latest version 0.6.x

### ISSUE THREAD

**Issue by mdillgen** [ozgurgunes/Sketch-Symbol-States#4]
![Screenshot 2020-02-01 22 41 47](https://user-images.githubusercontent.com/9297500/73599506-87ffc380-4544-11ea-8f73-cf0a5c67e021.png)

The latest release isn’t available. Downloading from here or even when trying to update directly from Sketch doesn’t work!

**Comment by ozgurgunes** [comment]
This has to be fixed now. Thanks for notice.
