### ISSUE TITLE
Feature request: apply state to all selected instances

### ISSUE THREAD

**Issue by xzenx** [ozgurgunes/Sketch-Symbol-States#5]
This plugin is really useful. A nice addition would be to be able to apply the saved symbol state to all selected instances. Currently you can only apply state to one selected instance.

Is this possible?

Thanks

**Comment by ozgurgunes** [comment]
Hi. Thanks for the feedback. I don't have any intend to fulfill your request because of performance issues. But I can suggest "Automate" plugin for doing that. Copy the instance, run "Automate > Symbol > Select Same Instances in Current Page", then "Automate > Layer > Paste and Replace".

**Comment by ozgurgunes** [comment]
This is done. May take some time depend on count of selection and complication of the symbol.
